package com.ecommerce.order.api.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.util.UUID;

/**
 * PlaceOrderRequest.
 *
 * idempotencyKey — generated by the CLIENT before submitting.
 * Why client-generated? Because if the server generated it, a network
 * timeout means the client never receives it and can't use it for retry.
 * Client generates UUID v4, stores it, sends with request. On retry,
 * sends same key. Server checks: if order with this key exists, return it.
 *
 * shippingAddress — full address snapshot. The client sends the address
 * to use for THIS order. Even if the user has a saved default address,
 * they might have selected a different one at checkout.
 */
public record PlaceOrderRequest(
    @NotNull
    UUID idempotencyKey,

    @NotNull @Valid
    ShippingAddressDto shippingAddress,

    String notes
) {
    public record ShippingAddressDto(
        @NotNull String fullName,
        @NotNull String line1,
        String line2,
        @NotNull String city,
        @NotNull String state,
        @NotNull String pincode,
        @NotNull String country,
        String phone
    ) {}
}
