apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://ecom-prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: zipkin
          urlDisplayLabel: View in Zipkin

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://ecom-zipkin:9411
    uid: zipkin
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://ecom-loki:3100
    editable: false
